// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixuukkxtpkbphcowxybb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4dXVra3h0cGticGhjb3d4eWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODM2MjgsImV4cCI6MjA1NTY1OTYyOH0.-5NPhpIHrCE79_vcbKSFPLHW3mHpWUlnke3BKjCZHBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);